### ISSUE TITLE
zip file is corrupted

### ISSUE THREAD

**Issue by njss** [kentsommer/VGG16-Image-Retrieval#1]
Hello,

I was trying to test your code, but i found that the dataset zip file is corrupted.
Also, when i try to run the code it seems that there some errors too? (python3 and spyder/anaconda)

Can I use this code to return all similarities values from each image on a folder in respect to all other images? I want to use those values to fill a distance matrix, to perform hierarchical clustering.

Thank you in advance,
Nelson

**Comment by kentsommer** [comment]
Hi njss, 

I've gone ahead and uploaded the dataset zip folder to google drive, let me know if you still have any issues. (see link in the updated README)

I'm using python2 so I'm not sure what the errors would be in python3, if you can give me more detail perhaps I can help. 

Depends on what you mean by similarity values? This currently outputs the feature vector corresponding to the second fully connected layer in the vgg network and computes distance (euc, cos, chev) from the given query image feature vector to every image feature vector in the "database". So the similarity score could be many things... for this demo I am using distance, but you could theoretically choose some other way to measure similarity. 

I'm closing this out, feel free to re-open if you have more questions
