### ISSUE TITLE
npz file is not uploaded properly 

### ISSUE THREAD

**Issue by chjiao** [kentsommer/VGG16-Image-Retrieval#2]
Seems that the vgg16_weights.npz file is not uploaded completely as it is too large. Can you upload it to google driver too? Thank you.

**Comment by liaocyintl-deprecated** [comment]
I have the problem too

**Comment by kentsommer** [comment]
Hey @chjiao and @liaocyintl,

I'll get one uploaded in about a week or so. Sorry for the delay!

**Comment by kentsommer** [comment]
Please use the new download_dataset_and_weights.sh script!
